- name: Ensure dependencies are present
  apt:
    name:
      - gnupg
      - ca-certificates
      - wget
    state: present
  become: true

- name: Add PostgreSQL APT repository
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  become: true

- name: Add PostgreSQL repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main
    filename: 'pgdg'
    state: present
  become: true

- name: Install PostgreSQL 16
  apt:
    name: postgresql-16
    state: present
    update_cache: yes
  become: true

- name: Copy pg_hba.conf
  copy:
    src: pg_hba.conf
    dest: /etc/postgresql/16/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: '0644'
  become: true

- name: Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started
    enabled: yes
  become: true

- name: Create PostgreSQL user paul
  become: true
  become_user: postgres
  postgresql_user:
    name: paul
    password: "democracyIsFragile"
    role_attr_flags: NOSUPERUSER,NOCREATEDB,NOCREATEROLE

- name: Create database paul
  become: true
  become_user: postgres
  postgresql_db:
    name: paul
    owner: paul

- name: Load schema
  become: true
  become_user: postgres
  postgresql_query:
    db: paul
    query: "{{ lookup('file', 'schema.sql') }}"
