- name: Install PostgreSQL 16 repository key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add PostgreSQL 16 repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    filename: "pgdg"
    state: present

- name: Install PostgreSQL 16
  apt:
    name: postgresql-16
    state: present
    update_cache: yes

- name: Ensure PostgreSQL is running and enabled
  service:
    name: postgresql
    state: started
    enabled: true

- name: Replace pg_hba.conf for scram-sha-256
  copy:
    src: pg_hba.conf
    dest: /etc/postgresql/16/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: "0644"

- name: Restart PostgreSQL
  service:
    name: postgresql
    state: restarted

- name: Create SQL user paul
  community.postgresql.postgresql_user:
    name: "{{ vault_postgres_user }}"
    password: "{{ vault_postgres_password }}"
    role_attr_flags: LOGIN
    state: present
    login_user: postgres
    login_password: "{{ vault_postgres_password }}"
    login_host: 127.0.0.1
    login_db: postgres

- name: Create paul database
  community.postgresql.postgresql_db:
    name: "{{ vault_postgres_db }}"
    owner: "{{ vault_postgres_user }}"
    encoding: UTF8
    template: template0
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    state: present

- name: Load schema
  become_user: postgres
  postgresql_query:
    db: "{{ vault_postgres_db }}"
    query: "{{ lookup('file', 'schema.sql') }}"
