# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alberic/G-CPP-500-COT-5-1-rtype-23

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alberic/G-CPP-500-COT-5-1-rtype-23

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alberic/G-CPP-500-COT-5-1-rtype-23/CMakeFiles /home/alberic/G-CPP-500-COT-5-1-rtype-23//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alberic/G-CPP-500-COT-5-1-rtype-23/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

Network/LobbyManager.o: Network/LobbyManager.cpp.o
.PHONY : Network/LobbyManager.o

# target to build an object file
Network/LobbyManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/Network/LobbyManager.cpp.o
.PHONY : Network/LobbyManager.cpp.o

Network/LobbyManager.i: Network/LobbyManager.cpp.i
.PHONY : Network/LobbyManager.i

# target to preprocess a source file
Network/LobbyManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/Network/LobbyManager.cpp.i
.PHONY : Network/LobbyManager.cpp.i

Network/LobbyManager.s: Network/LobbyManager.cpp.s
.PHONY : Network/LobbyManager.s

# target to generate assembly for a file
Network/LobbyManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/Network/LobbyManager.cpp.s
.PHONY : Network/LobbyManager.cpp.s

Network/Networkmanager.o: Network/Networkmanager.cpp.o
.PHONY : Network/Networkmanager.o

# target to build an object file
Network/Networkmanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/Network/Networkmanager.cpp.o
.PHONY : Network/Networkmanager.cpp.o

Network/Networkmanager.i: Network/Networkmanager.cpp.i
.PHONY : Network/Networkmanager.i

# target to preprocess a source file
Network/Networkmanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/Network/Networkmanager.cpp.i
.PHONY : Network/Networkmanager.cpp.i

Network/Networkmanager.s: Network/Networkmanager.cpp.s
.PHONY : Network/Networkmanager.s

# target to generate assembly for a file
Network/Networkmanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/Network/Networkmanager.cpp.s
.PHONY : Network/Networkmanager.cpp.s

Network/tcp_server.o: Network/tcp_server.cpp.o
.PHONY : Network/tcp_server.o

# target to build an object file
Network/tcp_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/Network/tcp_server.cpp.o
.PHONY : Network/tcp_server.cpp.o

Network/tcp_server.i: Network/tcp_server.cpp.i
.PHONY : Network/tcp_server.i

# target to preprocess a source file
Network/tcp_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/Network/tcp_server.cpp.i
.PHONY : Network/tcp_server.cpp.i

Network/tcp_server.s: Network/tcp_server.cpp.s
.PHONY : Network/tcp_server.s

# target to generate assembly for a file
Network/tcp_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/Network/tcp_server.cpp.s
.PHONY : Network/tcp_server.cpp.s

Network/udp_server.o: Network/udp_server.cpp.o
.PHONY : Network/udp_server.o

# target to build an object file
Network/udp_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/Network/udp_server.cpp.o
.PHONY : Network/udp_server.cpp.o

Network/udp_server.i: Network/udp_server.cpp.i
.PHONY : Network/udp_server.i

# target to preprocess a source file
Network/udp_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/Network/udp_server.cpp.i
.PHONY : Network/udp_server.cpp.i

Network/udp_server.s: Network/udp_server.cpp.s
.PHONY : Network/udp_server.s

# target to generate assembly for a file
Network/udp_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/Network/udp_server.cpp.s
.PHONY : Network/udp_server.cpp.s

main_server.o: main_server.cpp.o
.PHONY : main_server.o

# target to build an object file
main_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/main_server.cpp.o
.PHONY : main_server.cpp.o

main_server.i: main_server.cpp.i
.PHONY : main_server.i

# target to preprocess a source file
main_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/main_server.cpp.i
.PHONY : main_server.cpp.i

main_server.s: main_server.cpp.s
.PHONY : main_server.s

# target to generate assembly for a file
main_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/main_server.cpp.s
.PHONY : main_server.cpp.s

system/CollisionSystem.o: system/CollisionSystem.cpp.o
.PHONY : system/CollisionSystem.o

# target to build an object file
system/CollisionSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/system/CollisionSystem.cpp.o
.PHONY : system/CollisionSystem.cpp.o

system/CollisionSystem.i: system/CollisionSystem.cpp.i
.PHONY : system/CollisionSystem.i

# target to preprocess a source file
system/CollisionSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/system/CollisionSystem.cpp.i
.PHONY : system/CollisionSystem.cpp.i

system/CollisionSystem.s: system/CollisionSystem.cpp.s
.PHONY : system/CollisionSystem.s

# target to generate assembly for a file
system/CollisionSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/system/CollisionSystem.cpp.s
.PHONY : system/CollisionSystem.cpp.s

system/EnemySystem.o: system/EnemySystem.cpp.o
.PHONY : system/EnemySystem.o

# target to build an object file
system/EnemySystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/system/EnemySystem.cpp.o
.PHONY : system/EnemySystem.cpp.o

system/EnemySystem.i: system/EnemySystem.cpp.i
.PHONY : system/EnemySystem.i

# target to preprocess a source file
system/EnemySystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/system/EnemySystem.cpp.i
.PHONY : system/EnemySystem.cpp.i

system/EnemySystem.s: system/EnemySystem.cpp.s
.PHONY : system/EnemySystem.s

# target to generate assembly for a file
system/EnemySystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/system/EnemySystem.cpp.s
.PHONY : system/EnemySystem.cpp.s

system/GameServer.o: system/GameServer.cpp.o
.PHONY : system/GameServer.o

# target to build an object file
system/GameServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/system/GameServer.cpp.o
.PHONY : system/GameServer.cpp.o

system/GameServer.i: system/GameServer.cpp.i
.PHONY : system/GameServer.i

# target to preprocess a source file
system/GameServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/system/GameServer.cpp.i
.PHONY : system/GameServer.cpp.i

system/GameServer.s: system/GameServer.cpp.s
.PHONY : system/GameServer.s

# target to generate assembly for a file
system/GameServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/system/GameServer.cpp.s
.PHONY : system/GameServer.cpp.s

system/HealthSystem.o: system/HealthSystem.cpp.o
.PHONY : system/HealthSystem.o

# target to build an object file
system/HealthSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/system/HealthSystem.cpp.o
.PHONY : system/HealthSystem.cpp.o

system/HealthSystem.i: system/HealthSystem.cpp.i
.PHONY : system/HealthSystem.i

# target to preprocess a source file
system/HealthSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/system/HealthSystem.cpp.i
.PHONY : system/HealthSystem.cpp.i

system/HealthSystem.s: system/HealthSystem.cpp.s
.PHONY : system/HealthSystem.s

# target to generate assembly for a file
system/HealthSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/system/HealthSystem.cpp.s
.PHONY : system/HealthSystem.cpp.s

system/MovementSystem.o: system/MovementSystem.cpp.o
.PHONY : system/MovementSystem.o

# target to build an object file
system/MovementSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/system/MovementSystem.cpp.o
.PHONY : system/MovementSystem.cpp.o

system/MovementSystem.i: system/MovementSystem.cpp.i
.PHONY : system/MovementSystem.i

# target to preprocess a source file
system/MovementSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/system/MovementSystem.cpp.i
.PHONY : system/MovementSystem.cpp.i

system/MovementSystem.s: system/MovementSystem.cpp.s
.PHONY : system/MovementSystem.s

# target to generate assembly for a file
system/MovementSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/system/MovementSystem.cpp.s
.PHONY : system/MovementSystem.cpp.s

system/ProjectileSystem.o: system/ProjectileSystem.cpp.o
.PHONY : system/ProjectileSystem.o

# target to build an object file
system/ProjectileSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/system/ProjectileSystem.cpp.o
.PHONY : system/ProjectileSystem.cpp.o

system/ProjectileSystem.i: system/ProjectileSystem.cpp.i
.PHONY : system/ProjectileSystem.i

# target to preprocess a source file
system/ProjectileSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/system/ProjectileSystem.cpp.i
.PHONY : system/ProjectileSystem.cpp.i

system/ProjectileSystem.s: system/ProjectileSystem.cpp.s
.PHONY : system/ProjectileSystem.s

# target to generate assembly for a file
system/ProjectileSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/system/ProjectileSystem.cpp.s
.PHONY : system/ProjectileSystem.cpp.s

system/SpawnSystem.o: system/SpawnSystem.cpp.o
.PHONY : system/SpawnSystem.o

# target to build an object file
system/SpawnSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/system/SpawnSystem.cpp.o
.PHONY : system/SpawnSystem.cpp.o

system/SpawnSystem.i: system/SpawnSystem.cpp.i
.PHONY : system/SpawnSystem.i

# target to preprocess a source file
system/SpawnSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/system/SpawnSystem.cpp.i
.PHONY : system/SpawnSystem.cpp.i

system/SpawnSystem.s: system/SpawnSystem.cpp.s
.PHONY : system/SpawnSystem.s

# target to generate assembly for a file
system/SpawnSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/system/SpawnSystem.cpp.s
.PHONY : system/SpawnSystem.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... server"
	@echo "... Network/LobbyManager.o"
	@echo "... Network/LobbyManager.i"
	@echo "... Network/LobbyManager.s"
	@echo "... Network/Networkmanager.o"
	@echo "... Network/Networkmanager.i"
	@echo "... Network/Networkmanager.s"
	@echo "... Network/tcp_server.o"
	@echo "... Network/tcp_server.i"
	@echo "... Network/tcp_server.s"
	@echo "... Network/udp_server.o"
	@echo "... Network/udp_server.i"
	@echo "... Network/udp_server.s"
	@echo "... main_server.o"
	@echo "... main_server.i"
	@echo "... main_server.s"
	@echo "... system/CollisionSystem.o"
	@echo "... system/CollisionSystem.i"
	@echo "... system/CollisionSystem.s"
	@echo "... system/EnemySystem.o"
	@echo "... system/EnemySystem.i"
	@echo "... system/EnemySystem.s"
	@echo "... system/GameServer.o"
	@echo "... system/GameServer.i"
	@echo "... system/GameServer.s"
	@echo "... system/HealthSystem.o"
	@echo "... system/HealthSystem.i"
	@echo "... system/HealthSystem.s"
	@echo "... system/MovementSystem.o"
	@echo "... system/MovementSystem.i"
	@echo "... system/MovementSystem.s"
	@echo "... system/ProjectileSystem.o"
	@echo "... system/ProjectileSystem.i"
	@echo "... system/ProjectileSystem.s"
	@echo "... system/SpawnSystem.o"
	@echo "... system/SpawnSystem.i"
	@echo "... system/SpawnSystem.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

