services:
  - type: web
    name: agridistri
    env: python
    rootDir: backend_intranet
    buildCommand: |
      pip install -r requirements.txt
      cd ../agridistri-frontend && npm install && npm run build && cd ../backend_intranet
      python manage.py collectstatic --noinput
    startCommand: gunicorn intranet.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: intranet.settings
