
FROM debian:12-slim


RUN apt-get update && \
    apt-get install -y git build-essential && \
    rm -rf /var/lib/apt/lists/*


RUN git clone https://github.com/catseye/Befunge-93.git /befunge && \
    cd /befunge && make && cp bin/bef /usr/local/bin/befunge

RUN mkdir /app
WORKDIR /app

CMD ["/bin/bash"]
