FROM debian:12-slim

# Installer les dépendances pour compiler
RUN apt-get update && \
    apt-get install -y git build-essential && \
    rm -rf /var/lib/apt/lists/*

# Cloner et compiler Befunge
RUN git clone https://github.com/catseye/Befunge-93.git /befunge && \
    cd /befunge && make && cp bin/bef /usr/local/bin/befunge

# Créer le répertoire pour l'app
RUN mkdir /app
WORKDIR /app
