
FROM eclipse-temurin:21-jdk-jammy


SHELL ["/bin/bash", "-c"]

RUN apt-get update && \
    apt-get install -y maven && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app
WORKDIR /app

CMD ["/bin/bash"]
