FROM whanos-java:base

#  Copier pom.xml d'abord (cache)
COPY app/pom.xml /app/pom.xml
RUN mvn dependency:go-offline -B

#  Copier les sources
COPY app/ /app/

WORKDIR /app  #  PAS /app/app !

#  Compiler
RUN mvn clean package -DskipTests

#  Supprimer les sources
RUN rm -rf src/ pom.xml

#  Commande directe (pas sh -c)
CMD ["java", "-jar", "target/app.jar"]