# Whanos Base Image - Java SE 21
# Image officielle Eclipse Temurin (OpenJDK 21)
FROM eclipse-temurin:21-jdk-jammy

# Utiliser bash pour toutes les commandes (exigence du sujet)
SHELL ["/bin/bash", "-c"]

# Installer Maven (nécessaire pour "mvn package")
RUN apt-get update && \
    apt-get install -y maven && \
    rm -rf /var/lib/apt/lists/*

# Créer le répertoire de travail
RUN mkdir -p /app
WORKDIR /app

CMD ["/bin/bash"]