# Generated by Django 5.1 on 2024-11-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='image',
        ),
        migrations.AddField(
            model_name='listings',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
