# Generated by Django 5.1 on 2024-11-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_listings_image_listings_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='image_url',
        ),
        migrations.AddField(
            model_name='listings',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
