# Generated by Django 5.1 on 2024-11-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_listings_image_url_listings_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='image',
        ),
        migrations.AddField(
            model_name='listings',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
