# Generated by Django 5.1 on 2024-11-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_listings_image_listings_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='highest_price',
        ),
    ]
