# Generated by Django 5.1 on 2024-11-24 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listings_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='listing',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='aution_listings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='watclists', to='auctions.listings'),
        ),
    ]
