# Generated by Django 5.1 on 2024-11-24 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_watchlist_listing_watchlist_aution_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='aution_listings',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.listings'),
        ),
    ]
