# Generated by Django 5.2.4 on 2025-08-06 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0014_remove_watchlist_aution_listings_watchlist_listing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listings",
            name="highest_price",
        ),
    ]
