# Generated by Django 5.2.4 on 2025-08-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0015_remove_listings_highest_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="highest_bid",
            field=models.DecimalField(decimal_places=2, default="0.00", max_digits=10),
        ),
    ]
