# Generated by Django 5.2.4 on 2025-08-07 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0016_listings_highest_bid"),
        ("auctions", "0017_remove_bids_aution_listings_and_more"),
    ]

    operations = []
