FROM gcc:13.2

WORKDIR /app

RUN apt-get update && apt-get install -y make && rm -rf /var/lib/apt/lists/*

COPY . .

RUN make

RUN find . -type f ! -name 'compiled-app' -delete && \
    find . -type d -empty -delete

CMD ["./compiled-app"]
