FROM debian:12-slim

SHELL ["/bin/bash", "-c"]

RUN apt-get update && \
    apt-get install -y build-essential && \
    rm -rf /var/lib/apt/lists/*

RUN gcc --version

RUN mkdir -p /app
WORKDIR /app

CMD ["/bin/bash"]