##
## EPITECH PROJECT, 2025
## rr
## File description:
## rzr
##

NAME = ../zappy_ai
SRC = python_AI/main.py

all:
	@echo "Copie de $(SRC) vers $(NAME)..."
	cp $(SRC) $(NAME)
	chmod +x $(NAME)

clean:

fclean: clean
	rm -f $(NAME)

re: fclean all
