
FROM whanos-python:base

SHELL ["/bin/bash", "-c"]

WORKDIR /app

COPY . .

RUN if [ -f requirements.txt ]; then \
        pip install --no-cache-dir -r requirements.txt; \
    fi

CMD ["python", "-m", "app"]
