# images/javascript/Dockerfile.standalone
FROM whanos-javascript:base

# Copier l'application
COPY . /app
WORKDIR /app

# Installer les dépendances si package.json existe
RUN if [ -f package.json ]; then npm install; fi

# Commande pour lancer l'application
CMD ["node", "."]
